# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c135e0b3313b5523854cf0d6f5b43b6ac81f543b639e88d644d4e44e206e61fba2eb16a906d08b28c97b4d4de8758bd42fb8df23dc743c7b62255da43d0d73e9

test:
  secret_key_base: ccbea79826bf0d5be50ae63ccbf959aa60fd70f63a3dfb5431f753b306cb16cf26d5ca4ee99b2d2081d55b59291776c89e141c5504579cacaebccef1b0df4a32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
